InventoryManagement/InventoryManagementApp/Controllers/APi/SetupModule/CategorysController.cs
using App.Core.ViewModel.SetupModule;
using App.Service.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace InventoryManagementApp.Controllers.APi.SetupModule
{
    public class CategorysController : ApiController
    {
        private CategoryService _service = new CategoryService();
        // GET: api/Categorys
        public IHttpActionResult Get()
        {
            try
            {
                var entities = _service.GetAll().ToList();
                return Ok(entities);
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        // GET: api/Categorys/5
        public IHttpActionResult Get(int id)
        {
            try
            {
                var entity = _service.Get(id);
                return Ok(entity);
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        // POST: api/Categorys
        public IHttpActionResult Post([FromBody]CategoryViewModel vm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var entity = _service.Add(vm);
                    return Ok(entity);
                }
                else
                {
                    return BadRequest("Required Field Must Not be Empty!");
                }

            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        // PUT: api/Categorys/5
        public IHttpActionResult Put(int id, [FromBody]CategoryViewModel vm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var entity = _service.Update(id, vm);
                    return Ok(entity);
                }
                else
                {
                    return BadRequest("Required Field Must Not be Empty!");
                }

            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        // DELETE: api/Categorys/5
        public IHttpActionResult Delete(int id)
        {
            try
            {
                var entity = _service.Remove(id);
                return Ok(entity);
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }
    }
}

InventoryManagement/InventoryManagementApp/Controllers/CategoryController.cs
using App.Core.ViewModel.SetupModule;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryManagementApp.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category

        public ActionResult CategoryCreate()
        {
            var isActive = new CategoryViewModel() { IsActive = true };
            return View(isActive);
        }
    }
}

InventoryManagement/InventoryManagementApp/Controllers/SuppliersController.cs
using App.Core.ViewModel.SetupModule;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryManagementApp.Controllers
{
    public class SuppliersController : Controller
    {
        // GET: Suppliers
        public ActionResult SuppliersCreate()
        {
            var isActive = new SupplierViewModel() { IsActive = true };
            return View(isActive);
        }
    }
}

InventoryManagement/InventoryManagementApp/Views/Category/CategoryCreate.cshtml
@model App.Core.ViewModel.SetupModule.CategoryViewModel
@{
    ViewBag.Title = "CategoryCreate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
        <div class="panel panel-primary">
            <div class="panel-heading">Category Setup</div>
            <div class="panel-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, "Name*", htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.IsActive, "IsActive", htmlAttributes: new { @class = "control-label" })
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsActive)
                            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.HiddenFor(c => c.Id)
                        <input id="btnSubmit" type="button" value="Submit" class="btn btn-primary" />
                        <a class="btn btn-primary" href="@Url.Action("SuppliersCreate","Suppliers")">Next</a>
                    </div>
                }
            </div>
        </div>
        <div class="box box-primary">
            <div class="heading">Category List</div>
            <div class="box-body">
                <table id="categoryHistory" class="table table-bordered table-hover display">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Status</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section ViewSpecificJavascript
{
    <script src="~/Scripts/FormScript/SetupModule/categoryCreate.js"></script>
}