InventoryManagement/InventoryManagementApp/Controllers/APi/SetupModule/UnitsController.cs
using App.Core.ViewModel.SetupModule;
using App.Service.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace InventoryManagementApp.Controllers.APi.SetupModule
{
    public class UnitsController : ApiController
    {
        private UnitService _service = new UnitService();
        // GET: api/Units
        public IHttpActionResult Get()
        {
            try
            {
                var entities = _service.GetAll().ToList();
                return Ok(entities);
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        // GET: api/Units/5
        public IHttpActionResult Get(int id)
        {
            try
            {
                var entity = _service.Get(id);
                return Ok(entity);
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        // POST: api/Units
        public IHttpActionResult Post([FromBody]UnitViewModel vm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var entity = _service.Add(vm);
                    return Ok(entity);
                }
                else
                {
                    return BadRequest("Required Field Must Not be Empty!");
                }

            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        // PUT: api/Units/5
        public IHttpActionResult Put(int id, [FromBody]UnitViewModel vm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var entity = _service.Update(id, vm);
                    return Ok(entity);
                }
                else
                {
                    return BadRequest("Required Field Must Not be Empty!");
                }

            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        // DELETE: api/Units/5
        public IHttpActionResult Delete(int id)
        {
            try
            {
                var entity = _service.Remove(id);
                return Ok(entity);
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }
    }
}

InventoryManagement/InventoryManagementApp/Controllers/CustomersController.cs
using App.Core.ViewModel.SetupModule;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryManagementApp.Controllers
{
    public class CustomersController : Controller
    {
        // GET: Customers
        public ActionResult CustomersCreate()
        {
            var isActive = new CustomerViewModel() { IsActive = true };
            return View(isActive);
        }
    }
}

InventoryManagement/InventoryManagementApp/Controllers/ItemController.cs
using App.Core.Model.SetupModule;
using App.Core.ViewModel.SetupModule;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryManagementApp.Controllers
{
    public class ItemController : Controller
    {
        // GET: Item
        public ActionResult ItemCreate()
        {
            ViewBag.CategoryId = new SelectList(new List<Category>(), "Id", "Name");
            ViewBag.UnitId = new SelectList(new List<Unit>(), "Id", "Name");
            var isActive = new ItemViewModel() { IsActive = true };
            return View(isActive);
        }
    }
}

InventoryManagement/InventoryManagementApp/Controllers/UnitController.cs
using App.Core.ViewModel.SetupModule;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryManagementApp.Controllers
{
    public class UnitController : Controller
    {
        // GET: Unit
        public ActionResult UnitCreate()
        {
            var isActive = new UnitViewModel() { IsActive = true };
            return View(isActive);
        }
    }
}

InventoryManagement/InventoryManagementApp/Views/Unit/UnitCreate.cshtml
@model App.Core.ViewModel.SetupModule.UnitViewModel
@{
    ViewBag.Title = "UnitCreate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2">
        <div class="panel panel-primary">
            <div class="panel-heading">Unit Setup</div>
            <div class="panel-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, "Name*", htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.IsActive, "IsActive", htmlAttributes: new { @class = "control-label" })
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsActive)
                            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.HiddenFor(c => c.Id)
                        <input id="btnSubmit" type="button" value="Submit" class="btn btn-primary" />
                        <a class="btn btn-primary" href="@Url.Action("CustomersCreate","Customers")">Previous</a>
                        <a class="btn btn-primary" href="@Url.Action("ItemCreate","Item")">Next</a>
                    </div>
                }
            </div>
        </div>
        <div class="box box-primary">
            <div class="heading">Unit List</div>
            <div class="box-body">
                <table id="unitHistory" class="table table-bordered table-hover display">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Status</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section ViewSpecificJavascript
{
    <script src="~/Scripts/FormScript/SetupModule/unitsCreate.js"></script>
}