InventoryManagement/InventoryManagementApp/Controllers/APi/SetupModule/ItemsController.cs
using App.Core.ViewModel.SetupModule;
using App.Service.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace InventoryManagementApp.Controllers.APi.SetupModule
{
    public class ItemsController : ApiController
    {
        private ItemService _service = new ItemService();
        // GET: api/Items
        public IHttpActionResult Get()
        {
            try
            {
                var entities = _service.GetAll().ToList();
                return Ok(entities);
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        // GET: api/Items/5
        public IHttpActionResult Get(int id)
        {
            try
            {
                var entity = _service.Get(id);
                return Ok(entity);
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        // POST: api/Items
        public IHttpActionResult Post([FromBody]ItemViewModel vm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var entity = _service.Add(vm);
                    return Ok(entity);
                }
                else
                {
                    return BadRequest("Required Field Must Not be Empty!");
                }

            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        // PUT: api/Items/5
        public IHttpActionResult Put(int id, [FromBody]ItemViewModel vm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var entity = _service.Update(id, vm);
                    return Ok(entity);
                }
                else
                {
                    return BadRequest("Required Field Must Not be Empty!");
                }

            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }

        // DELETE: api/Items/5
        public IHttpActionResult Delete(int id)
        {
            try
            {
                var entity = _service.Remove(id);
                return Ok(entity);
            }
            catch (Exception e)
            {
                return BadRequest(e.Message);
            }
        }
    }
}

InventoryManagement/InventoryManagementApp/Controllers/ItemController.cs
using App.Core.Model.SetupModule;
using App.Core.ViewModel.SetupModule;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryManagementApp.Controllers
{
    public class ItemController : Controller
    {
        // GET: Item
        public ActionResult ItemCreate()
        {
            ViewBag.CategoryId = new SelectList(new List<Category>(), "Id", "Name");
            ViewBag.UnitId = new SelectList(new List<Unit>(), "Id", "Name");
            var isActive = new ItemViewModel() { IsActive = true };
            return View(isActive);
        }
    }
}

InventoryManagement/InventoryManagementApp/Controllers/UnitController.cs
using App.Core.ViewModel.SetupModule;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryManagementApp.Controllers
{
    public class UnitController : Controller
    {
        // GET: Unit
        public ActionResult UnitCreate()
        {
            var isActive = new UnitViewModel() { IsActive = true };
            return View(isActive);
        }
    }
}

InventoryManagement/InventoryManagementApp/Views/Item/ItemCreate.cshtml
@model App.Core.ViewModel.SetupModule.ItemViewModel
@{
    ViewBag.Title = "ItemCreate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">Item Setup</div>
            <div class="panel-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.CategoryId, "Category *", htmlAttributes: new { @class = "control-label" })
                            @Html.DropDownListFor(c => c.CategoryId, null, "", htmlAttributes: new { @class = "form-control"})
                            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.ItemsName, "ItemsName*", htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.ItemsName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ItemsName, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.PurchasePrice, "PurchasePrice", htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.PurchasePrice, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PurchasePrice, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Remark, "Remark", htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.Remark, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Remark, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.SalePrice, "SalePrice", htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.SalePrice, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.SalePrice, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.UnitId, "Unit *", htmlAttributes: new { @class = "control-label" })
                            @Html.DropDownListFor(c => c.UnitId, null, "", htmlAttributes: new { @class = "form-control", @tabindex = "22" })
                            @Html.ValidationMessageFor(model => model.UnitId, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.ReoderLevel, "ReoderLevel", htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.ReoderLevel, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ReoderLevel, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.IsActive, "IsActive", htmlAttributes: new { @class = "control-label" })
                            <div class="checkbox">
                                @Html.EditorFor(model => model.IsActive)
                                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.HiddenFor(c => c.Id)
                            <input id="btnSubmit" type="button" value="Submit" class="btn btn-primary" />
                            <a class="btn btn-primary" href="@Url.Action("UnitCreate","Unit")">Previous</a>

                        </div>
                    </div>

                }
            </div>
        </div>
        <div class="box box-primary">
            <div class="heading">Item List</div>
            <div class="box-body">
                <table id="itemHistory" class="table table-bordered table-hover display">
                    <thead>
                        <tr>
                            <th>Category</th>
                            <th>ItemsName</th>
                            <th>Unit</th>
                            <th>PurchasePrice</th>
                            <th>SalePrice</th>
                            <th>ReoderLevel</th>
                            <th>Remark</th>
                            <th>Status</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section ViewSpecificJavascript
{
   <script src="~/Scripts/FormScript/SetupModule/itemsCreate.js"></script>
}